version: '3.6'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      MUSIC_BLOG_DSN: postgresql+psycopg2://bloguser:blogpass@db/music_blog
      MUSIC_BLOG_UPLOADS: /app_data/uploads
      MUSIC_BLOG_DEMO: 'yes'
    networks:
      - default
    ports:
    - 80:80
    volumes:
    - ./app_data:/app_data
    restart: always

  db:
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: music_blog
      PGDATA: /var/lib/postgresql/data/music_blog
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
